apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-event-logger
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-event-logger
  template:
    metadata:
      labels:
        app: kube-event-logger
    spec:
      containers:
        - name: kube-event-logger
          image: kube-event-logger:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
