apiVersion: v1
kind: Service
metadata:
  name: kube-event-logger-service
spec:
  selector:
    app: kube-event-logger
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
